### ISSUE TITLE
This seems useful thanks

### ISSUE THREAD

**Issue by GoldDenis** [jwasham/coding-interview-university#1025]
I am new to programming and this looks like amazing roadmap, thanks! <3

**Comment by 89918082** [comment]
![img-4](https://user-images.githubusercontent.com/94897882/143004015-9ef8c86e-c367-4158-a148-75667eab2571.jpg)
![img-61](https://user-images.githubusercontent.com/94897882/143004296-e334b6a6-d99e-46a5-aa25-05c518d5a331.jpg)
