### ISSUE TITLE
i am not able to clone it on my device

### ISSUE THREAD

**Issue by fejiofor** [jwasham/coding-interview-university#1039]
Hi,

I was able to fork this repo, but when trying to clone it to my repo it didn't work. i got this error message in the terminal. 

error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libxcrun.dylib' (no such file)).

what does this mean? how do i fix it?

**Comment by dungxibo123** [comment]
Hi, can you clone the origin repo to your own device. I think the problem here is not the forked repo or the original repo, It might cause by your device
