### ISSUE TITLE
Translation to Persian (Farsi)

### ISSUE THREAD

**Issue by Kiarostami** [jwasham/coding-interview-university#1060]
Hi, 

I checked issues and understood someone was willing to translate the doc to Persian. However, I think they did not resume since there is no Persian in the "translation in progress" section. I would be happy if I could help you with this matter. 

BR
Sina

**Comment by jwasham** [comment]
Here is the translation in progress: https://github.com/jwasham/coding-interview-university/blob/main/translations/README-fa.md

I'll add a link under translations in progress.

Also I see this old PR but it was never requested to pull:
https://github.com/jwasham/coding-interview-university/pull/190

**Comment by jwasham** [comment]
Deferring to this issue: https://github.com/jwasham/coding-interview-university/issues/186

**Comment by Kiarostami** [comment]
Oh, that's cool! So, please let me know if I can contribute.
