### ISSUE TITLE
Wrong URL in Spanish translation.

### ISSUE THREAD

**Issue by GabrielVargasRV** [jwasham/coding-interview-university#1061]
It seems that the URL for the article 'Effective Whiteboarding during Programming Interviews' changed, when entering the site it redirects to a page where they are selling that domain.

**Comment by jwasham** [comment]
Thank you. That entire section has changed. See: https://github.com/jwasham/coding-interview-university#interview-process--general-interview-prep

**Comment by UltiRequiem** [comment]
Could we close this?

**Comment by jwasham** [comment]
sure
