### ISSUE TITLE
Org mode link points to a private video

### ISSUE THREAD

**Issue by sysupbda** [jwasham/coding-interview-university#1069]
[(maybe) Org Mode In Depth: Managing Structure (video)](https://www.youtube.com/watch?v=nsGYet02bEk)

Video cannot be watched because it is private

**Comment by zhengod** [comment]
您好，您的邮件我已经收到。谢谢！！希望你生活愉快！

**Comment by backeyshy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by jwasham** [comment]
Thank you. I removed the link.
