### ISSUE TITLE
Broken link: k-D Trees

### ISSUE THREAD

**Issue by KiwiB0y** [jwasham/coding-interview-university#1092]
Hi @jwasham,

I found a broken link in the [README.md](https://github.com/jwasham/coding-interview-university#readme) in the section [k-D Trees](https://github.com/jwasham/coding-interview-university#k-d-trees).

I tried to open the link, but it seems to be "no longer available due to a copyright claim by Kevin Wayne".
  - [Kd Trees (video)](https://www.youtube.com/watch?v=W94M9D_yXKk)

Thanks in advance!

**Comment by jwasham** [comment]
Thanks, I've removed it.
