### ISSUE TITLE
Update programming-language-resources.md #1111

### ISSUE THREAD

**Issue by bhumikatewary** [jwasham/coding-interview-university#1112]
Hello, I have made a PR as I have updated a README.md file and have added resources.
 Update programming-language-resources.md #1111
Please review it. Thank you

**Comment by chengjiangxiliu** [comment]
退订



***@***.***
 
From: John Washam
Date: 2022-04-01 23:43
To: jwasham/coding-interview-university
CC: Subscribed
Subject: Re: [jwasham/coding-interview-university] Update programming-language-resources.md #1111 (Issue #1112)
Closed #1112.
