### ISSUE TITLE
About Implementation of some Data Structures

### ISSUE THREAD

**Issue by SameerSahu007** [jwasham/coding-interview-university#1121]
Can I add Implementation of some data structures in Java. I think it would be helpful if someone get stuck while implementing it by themself.

**Comment by jwasham** [comment]
Hmm. This is interesting. However, maintaining a code repo and fixing bugs is not something I'm interested in. My own personal repos for implementations have been known to be incomplete and buggy. 

I think those studying it will have plenty of examples from the recommended textbooks and videos. I think that's good enough.
