### ISSUE TITLE
Translation: Brazilian Portuguese

### ISSUE THREAD

**Issue by avizmarlon** [jwasham/coding-interview-university#113]
Pull request: #115 
Anyone interested in helping please read below:

- Fork [my forked repo's branch](https://github.com/avizmarlon/google-interview-university/tree/ptbr-translation)
- Open an issue on my repo regarding the section you're going to work on.
- After translating your section, make a Pull Request, refer to it in the issue and close it.
- Reviewing each other work is recommended.
- Leave the formatting, whitespaces, etc. exactly like the original.
- Use spaces, not tabs. You can use Sublime Text or some other text editor to convert tabs to spaces.

**Comment by avizmarlon** [comment]
Pull request: #115

**Comment by devlware** [comment]
Any update on the translation?

**Comment by avizmarlon** [comment]
Yes, check: https://github.com/avizmarlon/google-interview-university/commits/ptbr-translation

**Comment by avizmarlon** [comment]
This issue will be updated when the translation is over. For now, all issues related to the PT-BR translation are being opened in my forked repo in the branch `ptbr-translation`. See them here: https://github.com/avizmarlon/google-interview-university/issues

**Comment by avizmarlon** [comment]
**Translation is finished.**

_Issue closed as per #115 and 6832a2c._
