### ISSUE TITLE
c++ post increment and decrement

### ISSUE THREAD

**Issue by Catmanaha** [jwasham/coding-interview-university#1180]
![Untitled](https://user-images.githubusercontent.com/68589407/180660911-0b79f7a0-4f61-49fa-a210-aaa7270f7151.png)

You wrote about post-(increment and decrement) but forgot about pre-(increment and decrement)

**Comment by jwasham** [comment]
it's on the second line as an order of precedence. Note that I did not create this cheat sheet.
