### ISSUE TITLE
Algorithm

### ISSUE THREAD

**Issue by nero0147** [jwasham/coding-interview-university#1227]
I need help in getting this done, Thank you!

Assume that you went for a grocery shopping where you bought several items
with different quantities. If you buy an item with a quantity of more than 2, you will get 10%
reduction on the item total price, if you buy an item with a quantity of more than 4, you will get
15% reduction on the item total price, and if you buy an item with a quantity of more than 9,
you will get 20% reduction on the item total price. The reductions are not cumulative. Given
a list of items with their IDs, quantities, and unit prices, and after analyzing the problem and
specifying the input and output data, write an algorithm in Pseudocode that performs as follows:
• prompt the user to enter the list of items,
• compute the total price of each item, and
• compute the total price of all the items, including the sale taxes.
Your answer should specify the input and output data, and the algorithm in Pseudocode.

**Comment by jwasham** [comment]
Sorry, this is not the place for asking programming interview questions.

**Comment by MissAbbey** [comment]
Nut to crack 😥
