### ISSUE TITLE
is it important to study math topics for coding interviews ?

### ISSUE THREAD

**Issue by Jeevasimba** [jwasham/coding-interview-university#1230]
Like Numbers theory : https://www.geeksforgeeks.org/number-theory-competitive-programming/

is it important to study math topics for coding interviews ?

**Comment by jwasham** [comment]
From that page, I'd only learn Factorial and Fibonacci, and Sieve of Eratosthenes. That's it. Any company that asks other math questions should look for a math major, not a CS major. Some do ask them, but I wouldn't prepare for it.

**Comment by muhammadbilal20130** [comment]
You should now understand maths topics but not as much in dept
