### ISSUE TITLE
How to attend interview in tech giant companies ?

### ISSUE THREAD

**Issue by Jeevasimba** [jwasham/coding-interview-university#1257]
I am from india.I am not graduated in good college.

I completed my college in 2021.

I saw in online there are three ways to attend interview in big tech companies.

1 . Crack coding competitions

     For example : Google's kick start , Facebook's hacker cup.
2 .  graduation in good college

      In good college big tech companies will come for campus interview to hiring the students in that college.
3 . recommend

      already existing employee will refer some one to atten the interview
Is there any other way to atten interview in big tech companies ?

I am currently working on Django.

I know android  development ,
           desktop app development , 
           react ,
           react-native,
           QT ,
           javascript ,
           javafx ,
           java ,
           c++ ,
          python ,
          JNI,
          Django

  
 My android app : https://play.google.com/store/apps/details?id=prad.mob.PCPS
 
 My desktop app (available for windows , linux and mac )  : https://pcoid.github.io/pcoid/ 

I worked 4 years on javafx and android development. But , I am not the expert .

I am currently  preparing for DSA for interviews.

I have a one doubt that is How to attend interview in tech giant companies ?

**Comment by jwasham** [comment]
This isn't the right place to ask for advice.

Connect with me on LinkedIn and I'll try to help: https://www.linkedin.com/in/johnawasham/
