### ISSUE TITLE
Do I have to pay a fortune to learn algorithms?

### ISSUE THREAD

**Issue by amorenew** [jwasham/coding-interview-university#1278]
[Algorithms in C, Parts 1-5 (Bundle), 3rd Edition](https://www.amazon.com/Algorithms-Parts-1-5-Bundle-Fundamentals/dp/0201756080)

Algorithms in the C language bundle costs 105$ and other books cost a lot of money.
Do I have to pay a fortune to learn algorithms? Is there another solution?
the same author made this course for free, is it a good alternative or is it a shallow course?
https://www.coursera.org/learn/algorithms-part1
https://www.coursera.org/learn/algorithms-part2

**Comment by amorenew** [comment]
@jwasham What do you think about universities' courses? 
like
https://www.youtube.com/playlist?list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb

**Comment by jwasham** [comment]
I watched all of those lectures. But when they start getting into proofs is where I say "no thanks".

The most important part of any of this learning is applying the data structures and algorithms to solve problems (I like LeetCode).
