### ISSUE TITLE
Structure 

### ISSUE THREAD

**Issue by Jeshi69** [jwasham/coding-interview-university#1343]
#include<stdio.h>

struct student {
    char name[10];
    int s-id;
    double cgpa;
    char email [10];
}
 student ob;
void main()
{   ob.name="himadry"
    ob.s-id=1201;
    ob.cgpa=3.90;
    ob.email="himadry@gmail.com";
    printf("%s",ob.name);
    printf("%d",ob.s-id);
    printf("%0.2lf",ob.cgpa);
    printf("%s",ob.email);
}
- plz identify the problems

**Comment by jwasham** [comment]
Please don't post any more issues like this. Only report issues related to the project.
