### ISSUE TITLE
Made C++ script to synchronize progress with GitHub

### ISSUE THREAD

**Issue by kacper-ragankiewicz** [jwasham/coding-interview-university#1353]
Hi jwasham,
you work really hard and I admire that. You're codding interview university is great to prepare for interviews in big 4, but I really miss the synchronization element for progress tracking on different devices, that's why I prepared module based on C++, can you take a look at it? 

https://github.com/kacper-ragankiewicz/coding-university

It's pull changes from Github, check if you mark today, if you're not, cin the number of chapters you have done, then it calculates how many left by parsing the md file and return you the estimated time to end the course.

**Comment by jwasham** [comment]
Interesting concept. 
My C++ skill is kind of rusty. If it works for you and gives you what you need, I encourage you to keep using it and improving it. Best of luck with your studies!

**Comment by kacper-ragankiewicz** [comment]
I'm improving, like you said, thanks for all, and I hope best for you and your projects!

p.s. remember to give me a star on repo, it's giving me lots of motivation to further work!
