### ISSUE TITLE
Made some changes

### ISSUE THREAD

**Issue by HimoriK** [jwasham/coding-interview-university#1359]
There's a lot of comments that trail off in the doc, I shortened it on my fork to make it easier to read.
As you say yourself, not all of the resources are necessary, especially not all the videos and materials.
Since most of the information will be forgotten anyway, why not reduce some of it?

**Comment by jwasham** [comment]
Thanks @HimoriK 
I remove resources from time to time in order to make it simpler. So it has gotten shorter over time, but it's still a lot. I'll continue to remove resources until there are only a handful per topic.
