### ISSUE TITLE
Study guide 

### ISSUE THREAD

**Issue by warrior8008** [jwasham/coding-interview-university#1370]
Thanks...!!

**Comment by Hackershivaye** [comment]
🙏

**Comment by jwasham** [comment]
@warrior8008 please help me understand. 
I've seen a lot of Issues created over the last few years that are like yours. It's an issue created with just a few words in the title, and it doesn't mention an issue with the repo. 
It must be some use of Issues that I don't understand. Is it a way of tagging a repo so others who don't know about the repo can see it?

**Comment by warrior8008** [comment]
@jwasham i understand your concern..i'm new here that's why i do this i delete this issue now

**Comment by jwasham** [comment]
No, it's fine, I just want to understand why Issues are created like this. I'll close it, but I really just want to know the use case since I see it so much. I'm not a github expert.

**Comment by jwasham** [comment]
Every time I ask no one answers. I honestly just wanna know. 😞
