### ISSUE TITLE
Wrong link to c book answers 

### ISSUE THREAD

**Issue by persep** [jwasham/coding-interview-university#1399]
In [README.md](
https://github.com/jwasham/coding-interview-university/blob/56e35bca62fc054cd8ec6423c5a2164a58649214/README.md?plain=1#L300C15-L300C15) file the link to [Answers to questions in the book](https://github.com/lekkas/c-algorithms)  points to a c library not to the answers of the book "The C Programming Language"

**Comment by jwasham** [comment]
Thanks, I've removed that link.
