### ISSUE TITLE
Translation: Urdu

### ISSUE THREAD

**Issue by ArsalanWahid** [jwasham/coding-interview-university#140]

**Comment by Shhzdmrz** [comment]
Want to work on Urdu translation. Please let me know if anyone working on it so we can divide the sections. Thanks

**Comment by WaqasEhmed** [comment]
It would be great.

**Comment by afaqahmedkhan** [comment]
> 
> 
> Want to work on Urdu translation. Please let me know if anyone working on it so we can divide the sections. Thanks

Hi, you guys still working on it, I could work with you guys on this

**Comment by ArsalanWahid** [comment]
I tried to translate the content in URDU but really there aren't enough users nor the demand for the content to be in URDU I may be wrong
