### ISSUE TITLE
Remote Jobs

### ISSUE THREAD

**Issue by Michealjordab55** [jwasham/coding-interview-university#1472]
Hello, I am looking for talented and professional freelancers, enter the necessary options:

    ~Data entry jobs

    ~Translation

    ~writing Jobs

    ~Typing jobs

    Payment: $1,500

    If you are interested kindly inbox me on my DM. Thank you

**Comment by Proxima45** [comment]
Bro i can do data entry job

**Comment by CodePioneer2** [comment]
-data entry: 6yoe
-translation: fin/eng
-typing: 90-100 wpm
