### ISSUE TITLE
static site for better UX ?

### ISSUE THREAD

**Issue by nongrata081** [jwasham/coding-interview-university#1485]
Hi @jwasham ! I thought it might be helpful to get a better UX for viewing the contents of this repo, while maintaining the ease of editing translations in .md files, and [implemented a static site generated from .md files with nextra](https://github.com/nongrata081/coding-uni-nextra-test)

[**Live Demo →**](https://coding-uni-nextra-test.vercel.app/)

Please let me know if you think it's ok and I should create a PR?

Kind regards and thanks for the great work with the coding uni 👍

**Comment by jwasham** [comment]
Thanks for putting this together, but I think the website does OK right now as-is. I've looked into github pages as well.
Thanks again.
