### ISSUE TITLE
Translation: Korean

### ISSUE THREAD

**Issue by amiii123malviya** [jwasham/coding-interview-university#1506]
Hello @jwasham,

I trust you are doing well ,

I would like to contribute in this great  project by translating the ReadMe.md file in "Korean" language and will be grateful if you will provide me this opportunity for  working this issue.

Best Regards
Amisha

**Comment by jwasham** [comment]
Of course - see #118 

This is how the translation looks right now:
https://github.com/jwasham/coding-interview-university/blob/main/translations/README-ko.md

**Comment by amiii123malviya** [comment]
Hello @jwasham ,

I hope you are doing well,

I just want to know that Readme.md file is available in translation in "Hindi" Language ..
Because I would Like to work on that too. I hope you consider my request .Thankyou

Regards
Amisha

**Comment by jwasham** [comment]
Feel free to work on whichever you wish.

I think the Hindi translation is complete:
https://github.com/jwasham/coding-interview-university/blob/main/translations/README-hi.md
