### ISSUE TITLE
Logical error and performance issues

### ISSUE THREAD

**Issue by shrivalidutt** [jwasham/coding-interview-university#1548]
The check for whether to create a new issue or update the existing one relies on the has_found output from the last_issue step. If the output is malformed or if there are unexpected results, it might not behave as intended. 

The max-concurrency is set to 3, which may still lead to delays; if possible, test with a higher value for performance.

**Comment by GoAheadShaun** [comment]
Hey, is it possible you've created an issue for the wrong repo?
