### ISSUE TITLE
Call from Google

### ISSUE THREAD

**Issue by vivekimsit** [jwasham/coding-interview-university#169]
I have been following you since a long time, I was just curious if you got call from Google, if yes, what was your experience?

**Comment by MrSourabh** [comment]
@vivekimsit You would like to see #131

**Comment by jwasham** [comment]
Thanks @MrSourabh 
@vivekimsit The good news is I got hired at Amazon.

**Comment by MrSourabh** [comment]
@jwasham Hey congrats John

**Comment by vivekimsit** [comment]
@jwasham cool. Actually I was interested in Google interview experience. But anyways you landed on great place 👍

**Comment by smy0906** [comment]
@jwasham Congratulations! I am really happy to hear that.

**Comment by Dangeranger** [comment]
@jwasham
Congratulations! We are all really stoked to hear you got the job you deserve.
It would be awesome to read a follow up post about your experience getting hired.
Congratulations!

**Comment by netspyer** [comment]
@jwasham Congratulations and very excited to hear that,  **Where there's a will, there's a way!**
