### ISSUE TITLE
Translation: Italian

### ISSUE THREAD

**Issue by ghost** [jwasham/coding-interview-university#170]
I'm willing to work on the Italian transition. [Here's my forked repository](https://github.com/pbroglio/coding-interview-university)

**Comment by jwasham** [comment]
Thanks @pbroglio!

**Comment by mirh** [comment]
I'm afraid this is dead in the water

**Comment by jwasham** [comment]
Agreed. There have been no pull requests and no placeholder readme exists. Will remove it.

**Comment by Lucas221-crypto** [comment]
Good day...
Firstly thank you for writing....
But I don't understand your discussion and support here!! 
 
  On Sun, Nov 21, 2021 at 7:48 PM, John ***@***.***> wrote:   


Closed #170.
