### ISSUE TITLE
1441 linter warnings for README.md

### ISSUE THREAD

**Issue by lachlan-eagling** [jwasham/coding-interview-university#172]
Markdown linter in Atom is returning 1441 warnings for formatting of markdown, mainly relating to indenting of lists/bullets.

**Comment by lachlan-eagling** [comment]
I have fixed these in a new [branch ](https://github.com/lachlan-eagling/coding-interview-university/tree/fix-172)of my forked repo here 619478dce9c6abb1627fe76b27e5e835f5310ac6.

**Comment by jwasham** [comment]
Thanks @lachlan-eagling but this leaves very odd spaces. I know the linter doesn't like my version, but I'd rather it be human usable and updatable. :)

**Comment by lachlan-eagling** [comment]
Thanks @jwasham appreciate the prompt response.
