### ISSUE TITLE
System Design Primer?

### ISSUE THREAD

**Issue by donnemartin** [jwasham/coding-interview-university#174]
Hi John, great resource!

I recently launched the [System Design Primer](https://github.com/donnemartin/system-design-primer) which might be a good addition under [System Design, Scalability, Data Handling](https://github.com/jwasham/coding-interview-university#system-design-scalability-data-handling).  The design section has a some good content on there already, let me know if you think this might be a good fit and where to best place it in that section, I'm happy to submit a PR.  Thanks!

![](https://camo.githubusercontent.com/e45e39c36eebcc4c66e1aecd4e4145112d8e88e3/687474703a2f2f692e696d6775722e636f6d2f6a6a3341354e382e706e67)

**Comment by jwasham** [comment]
Wow this is a thorough resource. Go ahead and do a PR.

**Comment by donnemartin** [comment]
Great!  I'll try to send the PR this week, thanks.
