### ISSUE TITLE
Amazon interview experience

### ISSUE THREAD

**Issue by vivekimsit** [jwasham/coding-interview-university#182]
After clearing their telephonic round. I was called for face to face rounds last week.
There were suppose to be four rounds and after third round HR told me that the panel
thinks that I am more fit for development role and she will let me know when to come for
that.

She also told me that I got good feedback regarding the coding part hence there will be
couple of rounds which will test my ability in JS and HTML etc.

Should I keep chasing HR and hope I am still in or should I leave my hope?

**Comment by imvetri** [comment]
Let HRs call you back rather than u following up with them. Wait for a week then probably u can call to know the feedback.

**Comment by vivekimsit** [comment]
Updating my progress. So, I got call from HR for next round and it was telephonic round.

After some casual introduction, I was given some CSS selectors and was asked to arrange them based on CSS specificity rules, I got bumped and told that I can't tell the exact priority but tried to convince him that I know the algorithm how rules are resolved, but he wasn't convinced.

Second, I was told to write `partial` function, I decided to go for `es6` syntax which I think didn't impress him, anyways my solution was correct but got stuck in passing in the correct context to the target function.

Later, I was asked what I have been doing recently, I told him that I am learning react and why I liked it. Being an AngularJs developer I was asked why I liked it and all and I told him things like redux and virtual DOM which makes it interesting, later we got caught in debates like:

- Why time travelling debugging? we don't need it.

-  Why immutability?

-  Why react when we can do similar things in AngularJS? (for this I told him that we can't because AngularJS works on polling via digest cycle and its philosophy is completely different)

Overall, I wasn't convinced with the interview, it didn't seem too fulfilling given the interviewer seem too opinionated, anyways its my personal opinion.

PS: I didn't get any HR call regarding the progress since week, it was my fifth and second last round so feeling a bit disappointed provided I cleared all the algorithm and data structure round.

**Comment by jwasham** [comment]
Please don't post interview questions here. Interviewers invest a lot of time in coming up with good questions.

**Comment by vivekimsit** [comment]
@jwasham I removed a lot of details from the description except the `partial` function, if you say I can remove it.

**Comment by jwasham** [comment]
I don't see any edits. I still see all the questions.

**Comment by vivekimsit** [comment]
Final update, I received mail from recruiter saying that I am rejected. This feels very funny to me, if anyone reads my update above can infer that.

I am not shattered but sad that sometimes interviews are not that fair. Please don't consider it as some backslash but just some reflections on present scenario.

**Comment by imvetri** [comment]
Rejections can teach a lot than success do. 👍

**Comment by AshishSaraswat** [comment]
Hi 
Even I appeared for Amazon,Chennai interview . After giving Hiring Manager round and getting a good feedback for the same I gave the Bar raiser round also. It has been more than a month but still I have not got any update from the HR. I tried to reach him but he did not even reply to my mail

**Comment by vivekimsit** [comment]
@imvetri I agree and that's what I wanted. But what I have learnt from the last round, nothing. Should I now memorize the CSS selector rule? no, in fact I like to write clean CSS, if needed I can check docs if needed.

**Comment by imvetri** [comment]
Learn if you wanted to learn. But don't put your effort just because amazon rejected you since you didn't knew it. I attend interviews just to learn things from others perspective.

**Comment by jwasham** [comment]
@vivekimsit Sorry about the interview result. The hardest part of an interview is not knowing where the interviewer thought you were lacking versus what you think they thought.
My only advice is to keep working and learning what you want to and what is practical for your projects (like @imvetri said). No one can know it all.

**Comment by vivekimsit** [comment]
@jwasham also, I think that telephonic interview dilutes the performance a lot. I should have told recruiter to go for face to face round.
