### ISSUE TITLE
Add "see also" links to standard libraries

### ISSUE THREAD

**Issue by jart** [jwasham/coding-interview-university#195]
Some people have an easier time learning theory when it's connected to practice.

Here are some cross-references you might be able to add to your to-do list.

- Hash Table
  - Java
    - [java.util.HashMap](https://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html) ([source](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/util/HashMap.java))
    - [java.util.LinkedHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashMap.html) (hash table + array)
    - [java.util.IdentityHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/IdentityHashMap.html) (use with  #interning)
    - [java.util.concurrent.ConcurrentHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html)
    - [java.util.HashSet](https://docs.oracle.com/javase/7/docs/api/java/util/HashSet.html)
    - [java.util.LinkedHashSet](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashSet.html)
    - [com.google.common.collect.ImmutableMap](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableMap.html)
    - [com.google.common.collect.ImmutableSet](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableSet.html)
    - [com.google.common.collect.HashMultimap](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/HashMultimap.html)
    - [com.google.common.collect.HashBiMap](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/HashBiMaphtml)
  - C++
    - [std::unordered_map](http://en.cppreference.com/w/cpp/container/unordered_map)
    - [std::unordered_set](http://en.cppreference.com/w/cpp/container/unordered_set)
    - [sparsehash](https://github.com/sparsehash/sparsehash)
  - Python
    - dict
    - set
  - JavaScript
    - object
    - [goog.object](https://google.github.io/closure-library/api/goog.object.html)
    - [goog.structs.Map](https://google.github.io/closure-library/api/goog.structs.Map.html)
    - [goog.structs.Set](https://google.github.io/closure-library/api/goog.structs.Set.html)
    - [goog.labs.struct.Multimap](https://google.github.io/closure-library/api/goog.labs.structs.Multimap.html)
- Red/black trees
  - Java
    - [java.util.TreeMap](https://docs.oracle.com/javase/7/docs/api/java/util/TreeMap.html)
    - [java.util.TreeSet](https://docs.oracle.com/javase/7/docs/api/java/util/TreeSet.html)
    - [com.google.common.collect.TreeMultimap](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/TreeMultimap.html)
  - C++
    - [std::map](http://en.cppreference.com/w/cpp/container/map)
    - [std::set](http://en.cppreference.com/w/cpp/container/set)
- AVL trees
  - JavaScript
    - [goog.structs.AvlTree](https://google.github.io/closure-library/api/goog.structs.AvlTree.html)
- Skip lists
  - Java
    - [java.util.concurrent.ConcurrentSkipListMap](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentSkipListMap.html)
    - [java.util.concurrent.ConcurrentSkipListSet](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentSkipListSet.html)
  - C++
    - [LevelDB skip.h](https://github.com/google/leveldb/blob/50e77a8263b19033b99ba49cdc45995595f1acf9/db/skiplist.h)
- Linked lists
  - Java
    - [java.util.concurrent.ConcurrentLinkedDeque](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedDeque.html)
    - [java.util.concurrent.LinkedBlockingDeque](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/LinkedBlockingDeque.html)
  - C++
    - [std::deque](http://en.cppreference.com/w/cpp/container/deque)
    - [std::forward_list](http://en.cppreference.com/w/cpp/container/forward_list)
- Heaps
  - Java
    - [java.util.PriorityQueue](https://docs.oracle.com/javase/7/docs/api/java/util/PriorityQueue.html)
    - [java.util.concurrent.PriorityBlockingQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/PriorityBlockingQueue.html)
    - [com.google.common.collect.MinMaxPriorityQueue](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/MinMaxPriorityQueue.html)
  - C++
    - [std::priority_queue](http://en.cppreference.com/w/cpp/container/priority_queue)
  - Python
    - [heapq](https://docs.python.org/2/library/heapq.html)
  - JavaScript
    - [goog.structs.PriorityQueue](https://google.github.io/closure-library/api/goog.structs.PriorityQueue.html)
- Arrays
  - Java
    - primitive[]
    - [java.util.ArrayList](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)
    - [java.util.ArrayDeque](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayDeque.html) (great for BFS)
    - [java.util.concurrent.CopyOnWriteArrayList](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html)
    - [java.util.concurrent.CopyOnWriteArraySet](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArraySet.html)
    - [java.util.concurrent.ArrayBlockingQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ArrayBlockingQueue.html)
    - [com.google.common.collect.ImmutableList](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableListhtml)
    - [com.google.common.collect.ArrayTable](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ArrayTable.html)
  - C++
    - Pointers
    - [std::vector](http://en.cppreference.com/w/cpp/container/vector)
  - Python
    - list
    - [np.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)
  - JavaScript
    - [goog.array](https://google.github.io/closure-library/api/goog.array.html)
    - [goog.vec](https://google.github.io/closure-library/api/goog.vec.html)
- Binary search
  - Java
    - [java.util.Collections#binarySearch](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#binarySearch(java.util.List,%20T))
    - [com.google.common.collect.ImmutableSortedMap](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableSortedMap.html)
    - [com.google.common.collect.ImmutableSortedSet](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ImmutableSortedSet.html)
  - C++
    - [std::binary_search](http://en.cppreference.com/w/cpp/algorithm/binary_search)
  - Python
    - [np.searchsorted](https://docs.scipy.org/doc/numpy/reference/generated/numpy.searchsorted.html)
    - [bisect](https://docs.python.org/2/library/bisect.html)
  - JavaScript
    - [goog.array.binarySearch](https://google.github.io/closure-library/api/goog.array.html#binarySearch)
- Bloom filters
  - Java
    - [com.google.common.hash.BloomFilter](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/hash/BloomFilter.html)
  - C++
    - [LevelDB bloom.cc](https://github.com/google/leveldb/blob/50e77a8263b19033b99ba49cdc45995595f1acf9/util/bloom.cc)
- Interning
  - Java
    - [String#intern](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#intern())
    - [com.google.common.collect.Interners](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/Interners.html)
  - Python
    - [intern(string)](https://docs.python.org/2/library/functions.html#intern)
- Memoization
  - Java
    - [Suppliers#memoize](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Suppliers.html)
  - JavaScript
    - [goog.memoize](https://google.github.io/closure-library/api/goog.memoize.html)
- LRU Caching
  - Java
    - [java.util.LinkedHashMap](http://stackoverflow.com/a/6400874) w/ accessOrder
    - [java.lang.ref.SoftReference](https://docs.oracle.com/javase/7/docs/api/java/lang/ref/SoftReference.html) w/ GC
    - [com.google.common.cache.CacheBuilder](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/cache/CacheBuilder.html#softValues()) w/ softValues()
  - Python
    - [functools.lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache)

I would go into graphs, but the topic is so complex. I will say that I like using `Multimap<T, T>` when I want a directed graph and don't care about edgeless vertices. There's also this relatively new [Guava Graphs](https://github.com/google/guava/wiki/GraphsExplained) library.

I've left out some stuff like `LinkedList` in Java. That's because there is no legitimate use case for that container. `ArrayDeque` is better than `LinkedList` when you want a `Deque`. Linked list containers only make sense in Java when you're doing concurrent stuff.

Please feel free to copy the information above wherever you guys like for the benefit of the public.

**Comment by jwasham** [comment]
Thanks @jart for this. 
I'd rather not add much more detail to the project flow at this point, as the project looks pretty overwhelming to a newcomer already. 
Feel free to add the resources to this language-specific page: https://github.com/jwasham/coding-interview-university/blob/master/programming-language-resources.md
