### ISSUE TITLE
CS:61B Videos

### ISSUE THREAD

**Issue by vsag** [jwasham/coding-interview-university#219]
UC Berkeley has removed almost all of its videos off of the web, so there will be many broken links. I am just saying shewchucks videos were amazing. This would be a good time to update the repo if you're  free.

**Comment by MrSourabh** [comment]
Yes, I've noticed it too. Many links are broken.  Do you have alternative links?

**Comment by vsag** [comment]
Sadly no they were unbelievable had I know it I would've downloaded them.

**Comment by jwasham** [comment]
This is really disappointing. I loved those videos. 
I'd appreciate it if you come across one you need (that is gone), check out Stanford, MIT, or elsewhere for high-quality lectures and replace it.

Cal ESG published Berkeley videos, not sure of affiliation: https://www.youtube.com/user/esgeecs/playlists

Stanford playlists: https://www.youtube.com/user/StanfordUniversity/playlists
MIT playlists: https://www.youtube.com/user/MIT/playlists
Harvard playlists: https://www.youtube.com/user/Harvard/playlists

**Comment by infuerno** [comment]
I found this:
http://www.infocobuild.com/education/audio-video-courses/computer-science/cs61b-spring2014-berkeley.html
which references content here:
https://archive.org/details/ucberkeley-webcast-PL-XXv-cvA_iAlnI-BQr9hjqADPBtujFJd

**Comment by vsag** [comment]
Wow that's really cool thanks for those, though I prefer the 2006 one, this has shewchuck and that's good enough for me thank you.

**Comment by jwasham** [comment]
I'm a little reticent to use them since UCB took their videos down for some reason that makes sense to them, but I feel better that these are from a dedicated space on Archive.org.
Would you mind updating the project to use these videos and replace the removed youtube ones?

**Comment by JIVS** [comment]
Any idea why those were removed?

**Comment by alex440440** [comment]
Apparently so that some people that like to make others life miserable will feel better with themselves https://reason.com/blog/2017/03/07/berkeley-deletes-200000-free-online-vide

**Comment by vsag** [comment]
I would like to do this, but I have no idea how GitHub works? What should I do? Fork your repo make changes in the read me file and make a new pull request? Is this method right? Or tell me how to do it, I am more than willing to help as they are really good videos and want others to access this.

**Comment by atultherajput** [comment]
@jwasham They have video on [Computer Science 61B - Fall 2006] (https://archive.org/details/ucberkeley-webcast-PL4BBB74C7D2A1049C) and here is whole [UC Berkeley Webcast Videos] (https://archive.org/details/ucberkeley-webcast)

**Comment by qkcire** [comment]
I would like to note that the UC Berkeley links still in fact work, however, in order to view them you must be logged into YouTube with a Berkeley account.

**Comment by jwasham** [comment]
Thanks for finding and fixing!
