### ISSUE TITLE
How to use it section?

### ISSUE THREAD

**Issue by AdityaSoni19031997** [jwasham/coding-interview-university#241]
https://github.com/jwasham/coding-interview-university#how-to-use-it

**How to use this section** 

Can someone explain to me how to use it??

I have tried the said things but nothing happen i guess..

**Comment by zpq456** [comment]
Oh.. i think... 
It's just a way of knowing how to progress.
you can branch code => code copy to your computer
and add 'Marked  x' => Your study ended here.
