### ISSUE TITLE
Translation: Japanese

### ISSUE THREAD

**Issue by Yang-33** [jwasham/coding-interview-university#257]
I want to contribute in Japanese.
I'll do my best.
[My fork](https://github.com/Yang-33/coding-interview-university) :fork_and_knife:

**Comment by Yang-33** [comment]
@jwasham  Can I write  "Japanese(日本語)" in Translations in progress to README.md ? (not README-jp.md)

**Comment by jwasham** [comment]
Thank you!

**Comment by ku6pk** [comment]
@Yang-33 よろしくお願いします、こちらからも翻訳してみたいのでやらせて頂きと嬉しいです。いかがでしょか？

**Comment by Yang-33** [comment]
@ku6pk さん、いいですね！
僕はかなり最初でやめてしまったのですがku6pkさんのペースに合わせてまた翻訳しようと思います。よろしくおねがいします。
詳しくは、私のfork内でメッセージのやり取りをお願いしてもよろしいですか？

**Comment by ku6pk** [comment]
@Yang-33さん、お疲れ様です！全然大丈夫です。では、Yang-33さんのforkでやり取りをしますのでよろしくお願いします。

**Comment by jwasham** [comment]
I've pulled the request. Closing. Thank you!
