### ISSUE TITLE
How many years I need to finish all of this stuff?

### ISSUE THREAD

**Issue by VanDalkvist** [jwasham/coding-interview-university#275]
Thank you for your great job!

But a little question here... Seriously, how much time? we all understand that we can't sit and learn. We should work for a living and spent time with our families. So, what do you think is the optimal estimate to get all of it done?

**Comment by jwasham** [comment]
There's no need to rush it. Learn it at your own pace. 
I gave myself a year, and was able to work on the plan full-time. Most people can't do that.

**Comment by Abson** [comment]
WOW, just one year to finish it that is incredibly difficult to me ! Many of knowledge was forget when  i learn the new. I have to spend some time to reviewing them.

**Comment by jwasham** [comment]
I spent a few months just reading stuff that I didn't need to know. I could have skipped reading the C and C++ books, the Algorithm Design Manual, Programming Pearls, and Algorithms and Programming by Shen. So removing those months, it took about 7 months.

**Comment by shivaprasad11may** [comment]
How many hours you spent..

**Comment by SaurabhMhaisekar** [comment]
I know this question is not directed to me :). Well I'm still into study but I've completed around 90% of what is listed in repo. It look me around 7 months. I hope that helps. Happy learning

**Comment by Abson** [comment]
The important question is How can i took about 7 months studying full-time without money and work.

**Comment by ankitsorathiya** [comment]
Great job done! What a motivation to those who are at least trying!
I would like to know how one gets and interview from google without having a good college degree or nobody known working in google.
Your response will be highly appreciated.

**Comment by VanDalkvist** [comment]
@SaurabhMhaisekar Did you spent all the time of your day or your spare time from job and family for learning?

**Comment by SaurabhMhaisekar** [comment]
Oh, I work full time. I usually spend some time from job for learning. I know it's sometimes crunch to do things while working and spending time away from family and friends. But it is possible. Personally for me 15 minutes meditation a day and pomodoro technique helped a lot. Hope this helps you. Happy learning :)

**Comment by rajfidence** [comment]
Allocating 30 hrs/week will help to complete this repo in  7-8 months. 
But it also depends on pace of learning.
Note : reviewing is important.

**Comment by VanDalkvist** [comment]
@rajfidence It's cool, but I have 1 or 2 hours per day for yourself, I have a wife and a daughter. I want to spend time with them. And I'm not the only one with it I suppose. So, the purpose is to learn most of the things and leave the 9-hour-per-day-job to spend time more productively with my family and with my hobbies.

**Comment by ashwin4ever** [comment]
I think dedicating an hour or 2 during the weekends and implementing or
learning any single algorithm or data structures during the weekdays which
would require about 30 to 45 mins would help. Another factor is, as you
progress the time spent to learn or internalize will reduce and you will
find yourself grasping at a faster rate than when you started. Also
remember interviews are tailored and specific, so preparing just the key
concepts and having a good grasp would get you through.

**Comment by rajfidence** [comment]
@VanDalkvist  I agree with your point. My views are more biased towards a student and un-married person.
To reduce number of hours you can do pair programming or also join slack channels, fb groups, etc to actively participate in discussion.

**Comment by VanDalkvist** [comment]
@rajfidence Pair programming is a great advice! Big thanks

**Comment by rohitkrishna094** [comment]
@SaurabhMhaisekar Since its almost 2 years since you mentioned that you completed 90% of this repo, I am just wondering what you are doing right now and how your life has changed? Were you able to get a job at Big N or maybe you have your own startup? Or maybe you are working on some new stuff while doing your Masters or PHD? Either way all the best. :)

**Comment by SaurabhSM** [comment]
@rohitkrishna094 i now work as software arch consultant, changed couple of big companies since last two years. I got better offer in my current company than one of big 3 was offering, I'm currently moving towards bigger goals. I am not big fan of PhD, so i'm not sure if i'll persue it in near future.
