### ISSUE TITLE
Clarification of `Implement a Vector` exercise

### ISSUE THREAD

**Issue by nerder** [jwasham/coding-interview-university#282]
As related to the Data Structure -> Arrays i don't fully understand the following statement:

> **new raw data array with allocated memory**
>- can allocate int array under the hood, just not use its features
> - start with 16, or if starting number is greater, use power of 2 - 16, 32, 64, 128

This exercise is suppose to be done just in `C`?

**Comment by SaurabhMhaisekar** [comment]
@nerder You can do exercise with C or C++. (Theoretically, you can do this exercise with any language which gives you way to manipulate memory directly)

**Comment by nerder** [comment]
Ok, thank you for the answer, i close this
