### ISSUE TITLE
Youtube video on garbage collection doesn't exist anymore

### ISSUE THREAD

**Issue by sankiran** [jwasham/coding-interview-university#312]
The video [Garbage collection (Java); Augmenting data str](https://www.youtube.com/watch?v=StdfeXaKGEc&list=PL-XXv-cvA_iAlnI-BQr9hjqADPBtujFJd&index=25) doesn't seem to exist anymore. 
cc: @jwasham

**Comment by jwasham** [comment]
Thank you. Please remove it and put in a pull request. :)

**Comment by sankiran** [comment]
Done. Raised a pull request #314
