### ISSUE TITLE
Question about the "How to use it" section

### ISSUE THREAD

**Issue by raini35** [jwasham/coding-interview-university#344]
I'm a bit confused on what this does. I followed the instructions, but I'm not exactly sure what I would mark as "x". 

"How to use it
Everything below is an outline, and you should tackle the items in order from top to bottom.

I'm using Github's special markdown flavor, including tasks lists to check progress.

Create a new branch so you can check items like this, just put an x in the brackets: [x]

Fork a branch and follow the commands below
git checkout -b progress

git remote add jwasham https://github.com/jwasham/coding-interview-university

git fetch --all

Mark all boxes with X after you completed your changes
git add .

git commit -m "Marked x"

git rebase jwasham/master

git push --force"

**Comment by jwasham** [comment]
The idea is to put an x in the [ ] . Like this: [x] and in markdown that check the box.

I added this how to save your progress **in your fork** but I'm not sure if it's correct. It looks wrong. You want to save progress to your fork, not the original. 

Can someone assist?

**Comment by raini35** [comment]
Oh I you have to go into markdown and mark the brackets with the x. Sorry I thought there was a command for that. 

Just to check my understanding, so every time I finished a section say: 
"- [ ] [Demystifying Tech Recruiting](https://www.youtube.com/watch?v=N233T0epWTs)" 

I would put an x in the bracket and then in my "progress" branch, do the following commands: 
git add .

git commit -m "Marked x"

git rebase jwasham/master

git push --force"

**Comment by raini35** [comment]
Oh you have to go into markdown and mark the brackets with the x. Sorry I thought there was a command for that.

Just to check my understanding, so every time I finished a section say:
"- [ ] Demystifying Tech Recruiting"

I would put an x in the bracket and then in my "progress" branch, do the following commands:
git add .

git commit -m "Marked x"

git rebase jwasham/master

git push --force"

**Comment by raini35** [comment]
Great. Thanks so much for the help!

**Comment by dhananjay0610** [comment]
Hey need help
I was not able to understand the process . Can you  please tel me in detail.
