### ISSUE TITLE
Question about Daily Plan

### ISSUE THREAD

**Issue by terencestone** [jwasham/coding-interview-university#358]
@jwasham - This may not be the exact right place to post this, but it could be helpful to future users. When you say that you choose one subject from the list below every day, are you referring to everything pictured in the attached image? If so, I'm wondering if you could suggest a preferred order of study, i.e. are all of these topics and sub-topics equally important? Also I'm curious, how long on average would you say you spent studying daily? Thanks for your consideration. 

![screen shot 2018-09-13 at 4 04 04 pm](https://user-images.githubusercontent.com/19293584/45512937-457ef080-b76f-11e8-9a28-1410c90ea5f9.png)

**Comment by jwasham** [comment]
Each item (linked lists, stack, etc) was meant to be 1 day, but some were so complex they stretched into more. 
I spent 8-12 hours per day. It's rare that people can do that.
