### ISSUE TITLE
Algorithms Sedgewick and Wayne (Video resource)

### ISSUE THREAD

**Issue by moonik** [jwasham/coding-interview-university#368]
Hi @jwasham. It seems that youtube deleted Sedgewick's channel and videos are not available anymore [Algorithms I](https://www.youtube.com/user/algorithmscourses/playlists?view=50&sort=dd&shelf_id=2), [Algorithms II](https://www.youtube.com/user/algorithmscourses/playlists?shelf_id=3&view=50&sort=dd).
But, I found these courses on coursera: [Part I](https://www.coursera.org/learn/algorithms-part1), [Part II](https://www.coursera.org/learn/algorithms-part2)

**Comment by shireeshaBongarala** [comment]
PR raised https://github.com/jwasham/coding-interview-university/pull/369

**Comment by moonik** [comment]
Updated the rest of the links with Sedgewick PR #370

**Comment by jwasham** [comment]
It makes me sad when good videos disappear!

Thank you both for fixing these links!
