### ISSUE TITLE
Jeff H Sipe YouTube channel is useful

### ISSUE THREAD

**Issue by haseebpvt** [jwasham/coding-interview-university#384]
I found this new YouTube channel: https://www.youtube.com/channel/UCs-7SAP1mhEQF1NlubjSzqQ/featured
Jeff H Sipe, the author of the channel has worked as a Google recruiter for 5 years. He make videos about Google interview and interviews in general.

I just found it to be very useful. His channel is new and he is making frequent videos, so you can get your questions answered quickly.

**Comment by jeffhsipe** [comment]
@haseebpvt - I sincerely appreciate the shout out!  I have created a new list of content to start producing and I will be releasing videos on a weekly basis again.  Stay tuned!
