### ISSUE TITLE
Raft consensus protocol

### ISSUE THREAD

**Issue by sevagh** [jwasham/coding-interview-university#385]
Hello,

First of all thanks for creating this.

I'm wondering if the Raft protocol should be included somewhere in this project as a gentle entrypoint into distributed systems and consensus.

The paper is very readable: https://raft.github.io/
Nice infographic here: http://thesecretlivesofdata.com/raft/

Raft is used in etcd, most of the Hashicorp tools (consul, vault, nomad). High relevance to industry IMO.

**Comment by jwasham** [comment]
Thanks, @sevagh but I think the system design area is already too large. If anything, I should remove some things, like several Google papers (since Google was the focus of this early on). As long as people understand what consensus systems are, that should be enough.

**Comment by sevagh** [comment]
Well the point is that Paxos and the other papers you mention aren't as understandable as Raft.

**Comment by jwasham** [comment]
I'll take a look and see what I can remove, and check this out.

**Comment by jwasham** [comment]
Added links in the System Design, Scalability, Data Handling section. Thanks!
