### ISSUE TITLE
Image not found : Cannot proxy the given URL

### ISSUE THREAD

**Issue by joonas-yoon** [jwasham/coding-interview-university#396]
Image which links `Coding at the whiteboard - from HBO's Silicon Valley` not found in section `What is it?`.

In current commits, the link refs [this](https://camo.githubusercontent.com/9e32acff11b04496eb14e09b198fcbb055c9ccf0/68747470733a2f2f646e67356c33717a7265616c362e636c6f756466726f6e742e6e65742f323031362f4175672f636f64696e675f626f6172645f736d616c6c2d313437303836363336393131382e6a7067) but was broken.

I don't know original picture. Fortunately, I got the picture from archive.is
https://archive.is/LX0ID/5fcb9f347487ecaf4feb02b1a57d255ff9e4429c

So, upload new picture here and I hope it will be useful for you.
![Coding at the whiteboard - from HBO's Silicon Valley](https://user-images.githubusercontent.com/9527681/49329978-1ab47380-f5cb-11e8-95d3-d841001e715a.png)

**Comment by joonas-yoon** [comment]
![image](https://user-images.githubusercontent.com/9527681/49330071-d2965080-f5cc-11e8-8d25-0cb401fa0fef.png)

I don't understand about this. The image is loaded well **sometimes**, and [this document](https://help.github.com/articles/about-anonymized-image-urls/#an-image-is-not-showing-up) is useful at this problem. How about use local image (by importing in this repo as a file) and links it?

**Comment by jwasham** [comment]
Thanks, I had gotten rid of the CDN for the old Googley as Heck site, and this was on it.

**Comment by jwasham** [comment]
Also updated another image, and got it via wayback machine. Thanks for your help!
