### ISSUE TITLE
Please add free and always-available public video sources

### ISSUE THREAD

**Issue by jwasham** [jwasham/coding-interview-university#40]
Some videos are available only by enrolling in a Coursera, EdX, or Lynda.com class. These are called MOOCs.

Sometimes the classes are not in session so you have to wait a couple of months, so you have no access. Lynda.com courses are not free.

I'd appreciate your help adding free and always-available public sources, such as YouTube videos to accompany the online course videos.  Do not remove the existing MOOC (either free or paid) videos.

I like using university lectures, but any videos of high quality (with good sound and clear voices) are welcome. Keep the number of videos for each subject small. Learners should be able to watch all the videos on a subject in a reasonable time. I'm guilty of adding too many videos for some subjects.

See #30 for history.

**Comment by anusakha** [comment]
tq

**Comment by STEW1327** [comment]
plex for now tv box

**Comment by jsroyal** [comment]
@jwasham Coursera , Edx , Udacity most of course are to access paid  and in the youtube there is lot of noise and confused.So please only link a reputable resourse.

**Comment by henryhoo** [comment]
Do you need any resource for file system?

**Comment by jwasham** [comment]
@henryhoo Some resources for file systems work would be useful in the "Additional learning" section: 
https://github.com/jwasham/google-interview-university#additional-learning
