### ISSUE TITLE
Question: Python or Java for Coding interview

### ISSUE THREAD

**Issue by halyph** [jwasham/coding-interview-university#403]
Hello John,
I'm writing here since comments are closed for this page https://startupnextdoor.com/ive-been-acquired-by-amazon/.

You've spent some time (see this repo) learning C/C++/Python for Amazon's interview. But, based on your blog posts you are working with Java.

If I ask you today, would you suggest to use Java (as coding interview "tool") instead of Python? Some people say that Python is very convenient for this type of interviews as Java is too verbose. 
But on the other hand, your Amazon interviewer(s) might prefer Java.

Could you please share your thoughts?

**Comment by jwasham** [comment]
Even though I use Java on a daily basis, I would still use Python for the interview because it's faster to write and takes less space on the whiteboard. 

More here: https://startupnextdoor.com/important-pick-one-language-for-the-coding-interview/

**Comment by jwasham** [comment]
You're welcome!
