### ISSUE TITLE
'Big And Little Endian' link is 403 forbidden

### ISSUE THREAD

**Issue by shihangwei** [jwasham/coding-interview-university#414]
Even More Knowledge
>    Endianness
>>        Big And Little Endian

link "https://www.cs.umd.edu/class/sum2003/cmsc311/Notes/Data/endian.html" is 403 forbidden

**Comment by arora-aditya** [comment]
Could possibly be replaced with: https://web.archive.org/web/20180107141940/http://www.cs.umd.edu:80/class/sum2003/cmsc311/Notes/Data/endian.html

**Comment by jwasham** [comment]
Thanks! Please make a pull request!

**Comment by shihangwei** [comment]
Thanks!
