### ISSUE TITLE
Flashcards available in Duolingo Tinycards 

### ISSUE THREAD

**Issue by meherranjan** [jwasham/coding-interview-university#429]
Hi All, 

I was really intrigued by flashcards and didn't quite like the Anki UI. So I went ahead and created a deck from the new 1800 flashcards, converted them to csv & finally importing it in Tinycards. 
I had to create Part I & Part II for 4 of the questions because Tinycards has 1000 letter limit for a card. So that's that. So yes, you could either: 

- Look up for **_Coding Interview University_** in the Duolingo Tinycards app
- Head over to https://tiny.cards/decks/MaUhepDw/coding-interview-university (the page crashes sometimes due to heavy js processing on the website. Mobile app is much better )

Thanks

**Comment by nitinsethi86** [comment]
Base news ! The Duolingo Tinycards app as been discontinued from September 2020.
