### ISSUE TITLE
Translation: German

### ISSUE THREAD

**Issue by koko-joe** [jwasham/coding-interview-university#433]
There wasn't an issue for a german translation yet.
I found an old Pull Request but the project seems to be abandoned.
Anyway you can find the repo [here](https://github.com/koko-joe/coding-interview-university).
It's still early in development.

**Comment by koko-joe** [comment]
Finished my part and opened Pull Request: https://github.com/jwasham/coding-interview-university/pull/434

**Comment by madhav5589** [comment]
This can be closed now. Thanks.
