### ISSUE TITLE
Translation: Traditional Chinese

### ISSUE THREAD

**Issue by flyotlin** [jwasham/coding-interview-university#506]
Hi jwasham, I found that the traditional Chinese translating program two years ago paused.
Therefore, I started to translate this repo again, over half has been translated.

有興趣一起翻譯的可以聯絡我，目前Even More Knowledge的後半部跟Additional books還沒翻譯好，另外也需要有人可以幫我看看有沒有翻譯不夠通順或錯誤的地方!

**Comment by shanshanc** [comment]
Hey flyotlin, I'm interested in joining you and would like to know where shall I start. Please let me know when you get a chance. Thx.

**Comment by blackza** [comment]
你找错人了。
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Shanshan Chen"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年4月5日(星期天) 中午12:49
 收件人:&nbsp;"jwasham/coding-interview-university"<coding-interview-university@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;Re: [jwasham/coding-interview-university] Translation: Traditional Chinese (#506)

 

 

 
Hey flyotlin, I'm interested in joining you and would like to know where shall I start. Please let me know when you get a chance. Thx.

**Comment by shanshanc** [comment]
ok, 我再試試, 謝謝

**Comment by Yilong-Lin** [comment]
> Hi jwasham, I found that the traditional Chinese translating program two years ago paused.
> Therefore, I started to translate this repo again, over half has been translated.
> 
> 有興趣一起翻譯的可以聯絡我，目前Even More Knowledge的後半部跟Additional books還沒翻譯好，另外也需要有人可以幫我看看有沒有翻譯不夠通順或錯誤的地方!

Hi @flyotlin, I would like to join this translation project as well. Please contact me to discuss where to begin with? thanks.

**Comment by WeiBoHaung** [comment]
嗨 @flyotlin，
我也想加入這個翻譯項目。
請與我聯繫以討論從哪裡開始
謝謝。

**Comment by flyotlin** [comment]
@Yilong-Lin  @WeiBoHaung  不好意思這麼晚回，我有把之前翻譯的東西上傳到我的repo裡面
https://github.com/flyotlin/coding-interview-university/blob/master/translations/README-tw.md
目前還在各個項目翻譯的部份。你們可以先去看一下，然後可以跟我討論你們想翻譯哪個部份。等整份文件翻譯完畢之後應該會再從頭審一遍。有什麼問題都可以再問我～

**Comment by flyotlin** [comment]
各位可以看一下這篇，並可以挑選一小部份開始翻譯
https://github.com/flyotlin/coding-interview-university/blob/master/tw_translation_progress_log.md

**Comment by flyotlin** [comment]
@jwasham I've finished the translation, can you merge it into the master branch?

**Comment by jwasham** [comment]
Sure, please do a pull request and link to the translation from README.md

**Comment by jwasham** [comment]
Thank you all so much for the great contributions!
