### ISSUE TITLE
I can't watch the video

### ISSUE THREAD

**Issue by 284324096** [jwasham/coding-interview-university#524]
Chinese mainland can not access videos like youtube and other websites. Can you make a mirror image? thanks

**Comment by Johnny4Fun** [comment]
目测不太现实，这些youtube视频是各个up发的，如果要镜像，可能还要一个个去征求作者的许可？

**Comment by ngzhio** [comment]
不会翻墙吗？

**Comment by zhangfeng-github** [comment]
Hi：
&nbsp;&nbsp; 这个问题不需要回复了，感谢！！









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shangzhi Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 晚上6:12
收件人:&nbsp;"jwasham/coding-interview-university"<coding-interview-university@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jwasham/coding-interview-university] I can't watch the video (#524)





 
不会翻墙吗？

**Comment by 284324096** [comment]
我下了好几个vpn软件，好像都用不了，各位有靠谱的vpn吗？

**Comment by ngzhio** [comment]
> 我下了好几个vpn软件，好像都用不了，各位有靠谱的vpn吗？

https://www.sednax.com/

**Comment by batouy** [comment]
不成问题的问题
