### ISSUE TITLE
Dead link to Khan Academy under #networking 

### ISSUE THREAD

**Issue by BMariscal** [jwasham/coding-interview-university#529]
**Section**: 
https://github.com/jwasham/coding-interview-university#networking 

**Link**:
Khan Academy link to https://www.khanacademy.org/computing/computer-science/internet-intro does not exist.

**Comment by rajat641** [comment]
> **Section**:
> https://github.com/jwasham/coding-interview-university#networking
> 
> **Link**:
> Khan Academy link to https://www.khanacademy.org/computing/computer-science/internet-intro does not exist.

![image](https://user-images.githubusercontent.com/8374949/82111937-609cc300-96fd-11ea-9ba7-66e567f031ff.png)

**Comment by rajat641** [comment]
@jwasham - Please let me know if the link is fine and I can fix it.

**Comment by jwasham** [comment]
Thanks all, I fixed it.
