### ISSUE TITLE
UniIntPrep

### ISSUE THREAD

**Issue by muralidharveluru** [jwasham/coding-interview-university#574]

**Comment by muralidharveluru** [comment]
Nice stuff

**Comment by jwasham** [comment]
Thank you. I have a question. I've seen several short one or two word issues like this, but they don't make sense to me. What does it mean?

**Comment by muralidharveluru** [comment]
Thanks for replying. The stuff you created helped me to refresh my uni subjects 17 years back. Interested to extend it but not immediately.. so to connect with your stuff and don't want to lost the link ..  let me know what you are expecting .

**Comment by jwasham** [comment]
Just curious. Over the last 2 weeks, there have been 2 or 3 issues created every day like yours that are very short. Did some website or blog link to the Issues page with instructions to make an issue?
I just want to know where these are coming from, so I'm asking.

**Comment by muralidharveluru** [comment]
You stuff showing in github trending. Very interesting. Sorry ,I don't know folks troubling you past 2 weeks . I Clicked as follower.
Thanks.

**Comment by jwasham** [comment]
Thanks Muralidhar! I appreciate the follow! I'm glad the project is helping.
