### ISSUE TITLE
Competitive Programming

### ISSUE THREAD

**Issue by shikha-16** [jwasham/coding-interview-university#588]
In my experience, competitive programming really helps brush up DSA skills. Taking part in contests, hackathons, etc really help you learn a lot by actually applying DSA. Maybe there should be a separate subtopic about this. I have many resources that would help. Let me know if I can take up this issue.

**Comment by destroyersp** [comment]
yes

**Comment by gtnevn** [comment]
hmmm

**Comment by jwasham** [comment]
Competitive programming can also be demoralizing, if you're still learning. Being able to do coding problems on Leetcode and other programming problem sites and interview books at your own pace is what I would recommend.

**Comment by aykutmayali** [comment]
yes :)

**Comment by HoweJI** [comment]
Hello,
	Due to personal reason, I want no more email.
	I’d like to check myself in the web.

Sent from Mail for Windows 10
