### ISSUE TITLE
 programming related issues

### ISSUE THREAD

**Issue by Hello-Saurabh** [jwasham/coding-interview-university#600]
In your document it is clearly mentioned that either one cplusplus Java python should be given a Priority in learning coding where I am learning C language does that make any difference, in my point of view I don't think that makes any difference
, and I am thinking of learning whole C language architecture then I will be changing my language from C to either one of them  which will be suitable for me in future.
 and I would love to know your suggestions for the sequence to learn full programming series like I started with C language with the help of book the C language by Dennis Ritchie and kernighan then now moving forward I started learning Data Structure along with discrete mathematics and don't know about what should I learn next.
I will truly appreciate and love to know your suggestions.

**Comment by jwasham** [comment]
I think C is a good language to have some experience with, and it's helpful in learning the fundamentals of computer science. It forces you to think about memory how data is laid out in memory. This is helpful in understanding one data structure vs another in terms of how you plan to access and change data efficiently. Once you're very comfortable with the fundamentals, there are many higher level languages that if you start with them, you could miss out on that understanding.

**Comment by rmsubham** [comment]
Thank you sir . 🙏❤️
