### ISSUE TITLE
Translation = Hindi

### ISSUE THREAD

**Issue by KaranJadaun** [jwasham/coding-interview-university#661]

**Comment by I-am-Harshdeep** [comment]
can you explain what is the issue?

**Comment by I-am-Harshdeep** [comment]
Do you me to convert README.md in Hindi?
I can do it if you allow me to do so?

**Comment by jwasham** [comment]
Hello,
This is the Issue for the Hindi translation: https://github.com/jwasham/coding-interview-university/issues/81

Translation so far: https://github.com/jwasham/coding-interview-university/blob/master/translations/README-hi.md

I'll close this as a duplicate.
