### ISSUE TITLE
engineering 

### ISSUE THREAD

**Issue by FlashFoxPRO** [jwasham/coding-interview-university#698]

**Comment by rishits321** [comment]
😀

**Comment by FlashFoxPRO** [comment]
i'm not engineering 😅

**Comment by pelumiojebode** [comment]
On Sun, Dec 20, 2020 at 6:30 PM FlashFoxPRO <notifications@github.com>
wrote:

> i'm not engineering 😅
>
😂🤣🤣

Just a coder 😟

**Comment by bplagmann1** [comment]
Do you help people get into coding. I’m looking to learn coding.

I want to change careers. Currently I’m a steering wheel holding and want
out of it.
Thanks in advance for your help

**Comment by FlashFoxPRO** [comment]
u play with me ok ? 😆

**Comment by pelumiojebode** [comment]
On Sun, Dec 20, 2020 at 9:54 PM FlashFoxPRO <notifications@github.com>
wrote:

> u play with me ok ? 😆
>

Okay
Howfar with my money ??????

**Comment by jwasham** [comment]
I've closed this and similar single-word or short phrase issues. I don't know where they are coming from or what they mean. They have become frequent in the last few months. If you can explain the purpose or their origin I'd appreciate it, but please don't respond, createing threads like these.
