### ISSUE TITLE
Page not found at README-ptbr.md

### ISSUE THREAD

**Issue by LeonardoFurtado** [jwasham/coding-interview-university#707]
There is a link going to a page not found, the link is "Recursos adicionais específicos a cada linguagem aqui." that is going to [here](https://github.com/jwasham/coding-interview-university/blob/master/translations/programming-language-resources.md)

**Comment by jwasham** [comment]
Thanks, fixed!

**Comment by Wortalcrmsoftware** [comment]
Wortal is a customer relationship management (CRM) software designed to help businesses manage their customer interactions, streamline sales processes, and enhance overall customer satisfaction. It provides a centralized platform to store and organize customer data, track leads and opportunities, and automate various sales and marketing tasks. it is cloud base software.it has uniques features likes lead management, [sales management](https://wortal.co/sales-management/), [employe management](https://wortal.co/inventory-Management/), [inventory management](https://wortal.co/employee-management/) and many more.
