### ISSUE TITLE
A translation into German would be good

### ISSUE THREAD

**Issue by LaStrixTV** [jwasham/coding-interview-university#710]

**Comment by fishc44** [comment]
The next time I will get a full year of order and then we can go back and forth with my family to get the info on my account for a week to help out and get a few more pictures and see how I am I have been looking for a new job I think it was the only one we can see for a full day so it's just like that we can get the next one for Christmas but it would probably have been one for Christmas but it was so hard to see you and your help with your Christmas pajamas and Christmas pajamas for Christmas pajamas and Christmas pajamas Christmas Christmas pajamas and Christmas .

**Comment by jwasham** [comment]
Here is the current translation: https://github.com/jwasham/coding-interview-university/blob/master/translations/README-de.md

**Comment by jwasham** [comment]
I just added a link to it from the main page.

**Comment by LaStrixTV** [comment]
> I just added a link to it from the main page.

thx
