### ISSUE TITLE
Amazon Triple Containing

### ISSUE THREAD

**Issue by liushuangddu** [jwasham/coding-interview-university#749]
Hi, I'm very glad to find you on this website. I'm a developer from China. Now I does working on Bluetooth Sigmesh . I plan to access the Amazon echo for my device , and then I recgnized before I need the BLE Mesh Credentials- A triple containing the OOB Type (Static only for now), OOB Data (pub key), and Device UUID.
But I has clicked entire website still connot find out the documentation for how to get my triple containing. 
May I get some help form you , very appreciate.

**Comment by pratikkhandale** [comment]
Yes why not. I'll be happy to help you

**Comment by jwasham** [comment]
Please contact each other outside this project. This is unrelated. Thanks!
