### ISSUE TITLE
About projects

### ISSUE THREAD

**Issue by alphaCS50** [jwasham/coding-interview-university#761]
Hello i too am a freshie or say i am a high school student and i have great desire to learn computers and how fo they work i read your resources it was awesome. 

But can you tell me about your projects you created to enhance your learning.???

**Comment by jwasham** [comment]
Hi,
Is this meant for anyone to answer?

**Comment by Korak-Sengupta** [comment]
Why am i receiving this texts ☹️

**Comment by jwasham** [comment]
@Korak-Sengupta you are probably subscribed to project updates. 

I'm closing this one.
I intentionally did not enable discussions in Github, and it's not something I want to manage either.

**Comment by Korak-Sengupta** [comment]
O yeah.....
