### ISSUE TITLE
Discrete Mathematics Resources not available.

### ISSUE THREAD

**Issue by omgupta1608** [jwasham/coding-interview-university#771]
I went down from the table of contents to 'Discrete Mathematics' but there are no resources or content available there. I may be missing something. Can anyone help me out please. @jwasham

**Comment by hrithik014** [comment]
What is your problem? Tell me.

I can try to solve your problem.

**Comment by jwasham** [comment]
If you search for "Discrete Mathematics" in the page, you'll see some links under "Video Series". One of the links (Shai Simonson videos) is broken, but the other 2 are good.
