### ISSUE TITLE
Outdated links about tries on the PT-BR version

### ISSUE THREAD

**Issue by micalevisk** [jwasham/coding-interview-university#772]
Hey!

I've notice that few videos under [Tries in the PT-BR translation](https://github.com/jwasham/coding-interview-university/blob/eb342c4452b4e8fe5fb620cd26b155f690ee092e/translations/README-ptbr.md#tries-ou-%C3%81rvore-de-prefixos) doesn't exist anymore but we can use the ones in `README.md` :)

thanks for this btw ^^

**Comment by jwasham** [comment]
Please put in a pull request

**Comment by micalevisk** [comment]
my bad. Here you go: (taken from [here](https://github.com/jwasham/coding-interview-university/blob/58fe0becc9b556ba4a8f47ae71cca275c7c96c55/translations/README-ptbr.md#tries-ou-%C3%A1rvore-de-prefixos))

- https://www.youtube.com/playlist?list=PLe-ggMe31CTe9IyG9MB8vt5xUJeYgOYRQ
- https://www.youtube.com/watch?v=buq2bn8x3Vo&index=3&list=PLe-ggMe31CTe9IyG9MB8vt5xUJeYgOYRQ
- https://www.youtube.com/watch?v=LelV-kkYMIg&index=2&list=PLe-ggMe31CTe9IyG9MB8vt5xUJeYgOYRQ
- https://www.youtube.com/watch?v=00YaFPcC65g&list=PLe-ggMe31CTe9IyG9MB8vt5xUJeYgOYRQ&index=2

You can replace them by these: (taken from main [README.md](https://github.com/jwasham/coding-interview-university/blob/eb342c4452b4e8fe5fb620cd26b155f690ee092e/README.md#L1053)):
- https://www.coursera.org/learn/algorithms-part2/home/week/4
- https://www.coursera.org/learn/algorithms-part2/lecture/CPVdr/r-way-tries
- https://www.coursera.org/learn/algorithms-part2/lecture/yQM8K/ternary-search-tries
- https://www.coursera.org/learn/algorithms-part2/lecture/jwNmV/character-based-operations

Also https://www.topcoder.com/community/data-science/data-science-tutorials/using-tries could be replaced by https://www.topcoder.com/community/competitive-programming/tutorials/using-tries because the former is redirect to the later already.

**Comment by jwasham** [comment]
Thanks, done!
