### ISSUE TITLE
Translation: Spanish

### ISSUE THREAD

**Issue by jwasham** [jwasham/coding-interview-university#80]
This is a thread for coordinating work on the Spanish translation.

**Comment by dapp1990** [comment]
Hey guys I'd like to help out with the Spanish translation, how can I get started?

**Comment by dossorio** [comment]
Hi @dapp1990  ! I have added some issues with chunks that need translation, so we all know what we are up to https://github.com/dossorio/google-interview-university/issues
Create a pr against this repo, we will finally merge #78 when we are done

Cheers @dapp1990 !

**Comment by dapp1990** [comment]
Got it!

Thanks @dossorio

**Comment by kebab901** [comment]
@jwasham the first thing I noted is that **"Ciencia de computadores" is wrong**. The correct translation for spanish language is "[Ciencias de la Computación](https://es.wikipedia.org/wiki/Ciencias_de_la_computaci%C3%B3n)".

**Comment by MrSourabh** [comment]
@kebab901 please feel free to update translation and create a PR.

**Comment by dossorio** [comment]
Hi @kebab901 ! Thank you very much for your suggestion ! That has been corrected, and will be available once this pr is merged https://github.com/jwasham/google-interview-university/pull/78/files#diff-05fe7da931ae7532c54b81f08d97421eR7 

Would you like to give us a hand ? Pick an issue from [here](https://github.com/dossorio/google-interview-university/issues) and start translating !! :)

**Comment by alangarciar** [comment]
Just so everyone translating is on the same page, what verb conjugations should we use,
formal (usted) or informal (tú/vos)?

**Comment by dossorio** [comment]
Hi @alangarciar !

I guess the more informal way is fine, from dev to dev :)

**Comment by llealgt** [comment]
My original language is spanish , so i would like to work on this translation, what do i have to do?

**Comment by dossorio** [comment]
Hi @llealgt !!

Find some instructions [here](https://github.com/jwasham/google-interview-university/pull/78#issue-196754356) 

Let me know if you need any help.

Thanks !! 👍

**Comment by sirgalleto** [comment]
Ooh, this is a nice proposal. I hope help in the next weeks. 

Cheers!

**Comment by DeusArcana** [comment]
I want to help on this... I hope we can translate this to neutral spanish, just for being kind of Universal. 

Cheers!

**Comment by dossorio** [comment]
> I want to help on this... I hope we can translate this to neutral spanish, just for being kind of Universal.

Find some instructions [here](https://github.com/jwasham/google-interview-university/pull/78#issue-196754356) 

Cheers !

**Comment by ArCiGo** [comment]
How can I help? I'm interested :)

**Comment by jwasham** [comment]
We can close this now, yes?

**Comment by dossorio** [comment]
@jwasham Yes! feel free to close it ! :)
