### ISSUE TITLE
Get ride of dead links on `README.md` file

### ISSUE THREAD

**Issue by micalevisk** [jwasham/coding-interview-university#825]
Hey! I've use the link checker https://github.com/lycheeverse/lychee against your [`README.md`](https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md), and found a few broken links:

1. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L884
2. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1005
3. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1006
4. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1223
5. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1314
6. HTTP timeout https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1586
7. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1724
8. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1773
9. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1781
10. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1783
11. https://github.com/jwasham/coding-interview-university/blob/0e572695740520ccad9f71be684645510dedc339/README.md#L1925

btw do you think that could be cool to use their [GitHub Action `lychee-action`](https://github.com/lycheeverse/lychee-action) to write GH workflows that will perform links checker against all Pull Requests, and every month, look up for broken links (`404` or `401` responses in Lychee summary) and create automated issues to let you aware of they? I can prototype and test this in a fork and make a PR if you want :smile:

---

<details>
<summary>Lychee summary:</summary>

```
📝 Summary
---------------------
🔍 Total..........802
✅ Successful.....789
⏳ Timeouts.........2
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors..........11

Errors in README.md
⧖ http://www.algorithm.cs.sunysb.edu/algowiki/index.php/The_Algorithms_Design_Manual_(Second_Edition)
✗ https://www.youtube.com/watch?v=uFKi2-J-6II&list=PLCiOXwirraUCBE9i_ukL8_Kfg6XNv7Se8&index=3 (HTTP status client error (404 Not Found) for url (https://img.youtube.com/vi/uFKi2-J-6II/0.jpg))
✗ https://www.youtube.com/watch?v=LKe7xK0bF7o&list=PLCiOXwirraUCBE9i_ukL8_Kfg6XNv7Se8&index=2 (HTTP status client error (404 Not Found) for url (https://img.youtube.com/vi/LKe7xK0bF7o/0.jpg))
✗ http://blog.panictank.net/category/algorithmndesignmanualsolutions/page/2/ (HTTP status server error (500 Internal Server Error) for url (http://blog.panictank.net/category/algorithmndesignmanualsolutions/page/2/))
✗ https://www.interviewbit.com/invite/icjf (HTTP status client error (404 Not Found) for url (https://www.interviewbit.com/invite/icjf))
✗ http://www.indieflashblog.com/how-to-create-an-asynchronous-multiplayer-game.html (HTTP status client error (404 Not Found) for url (http://www.indieflashblog.com/how-to-create-an-asynchronous-multiplayer-game.html))
✗ https://www.youtube.com/watch?v=W94M9D_yXKk (HTTP status client error (404 Not Found) for url (https://img.youtube.com/vi/W94M9D_yXKk/0.jpg))
✗ https://www.youtube.com/watch?v=phxsQrZQupo&list=PL_2Bwul6T-A7OldmhGODImZL8KEVE38X7 (HTTP status client error (404 Not Found) for url (https://img.youtube.com/vi/phxsQrZQupo/0.jpg))
✗ https://www.youtube.com/watch?v=L1jjXGfxozc (HTTP status client error (404 Not Found) for url (https://img.youtube.com/vi/L1jjXGfxozc/0.jpg))
✗ https://www.udacity.com/course/machine-learning-engineer-nanodegree-by-google--nd009 (HTTP status client error (404 Not Found) for url (https://www.udacity.com/course/machine-learning-engineering-nanodegree--nd009t))
✗ https://www.tensorflow.org/versions/r0.11/tutorials/index.html (HTTP status client error (404 Not Found) for url (https://www.tensorflow.org/versions/r0.11/tutorials/index.html))
⧖ http://www.celeryproject.org/
✗ http://www.thisismetis.com/explore-data-science (HTTP status client error (404 Not Found) for url (https://www.thisismetis.com/explore-data-science))
```

</details>

**Comment by jwasham** [comment]
I think this would be helpful!
Go ahead and give it a try.

**Comment by JaeQueCoder** [comment]
Great work finding dead links @micalevisk

**Comment by jwasham** [comment]
Closing issue: PR: https://github.com/jwasham/coding-interview-university/pull/1028
