### ISSUE TITLE
Small correction in pt-br translation

### ISSUE THREAD

**Issue by AndreArrebola** [jwasham/coding-interview-university#858]
The portuguese-Brazil translation is pretty good, but there is a minor error that would be good to correct for consistency.

It's located in **Antes de Começar>1. Você não se lembrará de tudo**, corresponding to **Before you Get Started>1. You Won't Remember it All** in the original Readme.

The one in the document:
Assisti a horas de vídeos e fiz anotações e meses depois havia muito que eu não lembrava. Eu passei 3 dias revisando minhas **anotaçes** e fazendo flashcards para que eu pudesse relembrar.

Corrected phrase:
Assisti a horas de vídeos e fiz anotações e meses depois havia muito que eu não lembrava. Eu passei 3 dias revisando minhas **anotações** e fazendo flashcards para que eu pudesse relembrar.

**Comment by jwasham** [comment]
Fixed! Thanks!
