### ISSUE TITLE
Translation: Russian

### ISSUE THREAD

**Issue by Ilyushin** [jwasham/coding-interview-university#87]
- [x] What is it
- [x] Table of Contents
- [x] What is it?
- [x] Why use it?
- [x] How to use it
- [x] Don't feel you aren't smart enough
- [x] About Video Resources
- [x] Interview Process & General Interview Prep
- [x] Pick One Language for the Interview
- [x] Book List
- [x] Before you Get Started
- [x] What you Won't See Covered
- [x] Prerequisite Knowledge
- [x] The Daily Plan
- [x] Algorithmic complexity / Big-O / Asymptotic analysis
- [x] Data Structures
- [x] Arrays
- [x] Linked Lists
- [x] Stack
- [x] Queue
- [x] Hash table
- [x] More Knowledge
- [x] Binary search
- [x] Bitwise operations
- [x] Trees(@Ilyushin)
- [x] Trees - Notes & Background (@Ilyushin)
- [x] Binary search trees: BSTs
- [x] Heap / Priority Queue / Binary Heap (@Ilyushin)
- [x] balanced search trees (general concept, not details) (@Ilyushin)
- [x] traversals: preorder, inorder, postorder, BFS, DFS (@Ilyushin)
- [x] Sorting (@Ilyushin)
- [x] selection (@Ilyushin)
- [x] insertion (@Ilyushin)
- [x] heapsort (@Ilyushin)
- [x] quicksort (@Ilyushin)
- [x] merge sort
- [x] Graphs
- [x] directed
- [x] undirected
- [x] adjacency matrix
- [x] adjacency list
- [x] traversals: BFS, DFS
- [x] Even More Knowledge
- [x] Recursion
- [x] Dynamic Programming
- [x] Object-Oriented Programming
- [x] Design Patterns
- [x] Combinatorics (n choose k) & Probability (@Ilyushin)
- [x] NP, NP-Complete and Approximation Algorithms (@Ilyushin)
- [x] Caches (@Ilyushin)
- [x] Processes and Threads (@Ilyushin)
- [x] Papers
- [x] Testing (@g7tro4w)
- [x] Scheduling (@g7tro4w)
- [x] Implement system routines (@g7tro4w)
- [x] String searching & manipulations (@g7tro4w)
- [x] Tries (@g7tro4w)
- [x] Floating Point Numbers (@g7tro4w)
- [x] Unicode (@g7tro4w)
- [x] Endianness (@g7tro4w)
- [x] Networking (@g7tro4w)
- [x] System Design, Scalability, Data Handling (if you have 4+ years experience) (@g7tro4w)
- [x] Final Review (@mikhailusov)
- [x] Coding Question Practice (@mikhailusov)
- [x] Coding exercises/challenges (@mikhailusov)
- [x] Once you're closer to the interview (@mikhailusov)
- [x] Your Resume (@mikhailusov)
- [x] Be thinking of for when the interview comes (@mikhailusov)
- [x] Have questions for the interviewer (@mikhailusov)
- [x] Once You've Got The Job (@mikhailusov)
- [x] Additional Books (@Ilyushin)
- [x] Additional Learning (@Ilyushin)
- [x] Compilers (@Ilyushin)
- [x] Emacs and vi(m)
- [x] Unix command line tools
- [x] Information theory
- [x] Parity & Hamming Code
- [x] Entropy
- [x] Cryptography
- [x] Compression
- [x] Computer Security
- [x] Garbage collection (@Ilyushin)
- [x] Parallel Programming (@Ilyushin)
- [x] Messaging, Serialization, and Queueing Systems
- [ ] A*
- [x] Fast Fourier Transform
- [x] Bloom Filter
- [x] HyperLogLog
- [x] Locality-Sensitive Hashing
- [x] van Emde Boas Trees
- [x] Augmented Data Structures
- [x] Balanced search trees
- [ ] AVL trees
- [ ] Splay trees
- [ ] Red/black trees
- [ ] 2-3 search trees
- [x] 2-3-4 Trees (aka 2-4 trees)
- [x] N-ary (K-ary, M-ary) trees
- [x] B-Trees
- [x] k-D Trees
- [x] Skip lists
- [x] Network Flows
- [x] Disjoint Sets & Union Find
- [x] Math for Fast Processing
- [x] Treap
- [x] Linear Programming (@Ilyushin)
- [x] Geometry, Convex hull
- [ ] Discrete math
- [ ] Machine Learning (@Ilyushin)
- [ ] Additional Detail on Some Subjects
- [ ] Video Series
- [ ] Computer Science Courses

**Comment by Hemko** [comment]
Hi @Ilyushin i want to help with translation. Can you write me how to contribute in this project?

**Comment by Ilyushin** [comment]
Hi @Hemko! It's cool:) You can fork https://github.com/Ilyushin/google-interview-university and translate all starting from 'Graphs' paragraph. When a paragraph will be translated, you can do pull request.

**Comment by Julila** [comment]
Hi , I would like to work on the translation too. Could you say me with which part should i start ?

**Comment by Hemko** [comment]
Hi @Julila.
I think you can just select any part of this plan and let us know about it.
You can start from the end of the document.

**Comment by Ilyushin** [comment]
Hi, @Julila!
Do you have any news about translation?

**Comment by fadilmamedov** [comment]
Hi, @Ilyushin! As far as I can see there is still no translation. Do you mind if I take care of it?

**Comment by Ilyushin** [comment]
Hi @fadilmamedov, no doubt, you can help us, but only say what piece of the text you are planning to translate.

**Comment by Ilyushin** [comment]
@fadilmamedov This is a branch where we are working https://github.com/Ilyushin/google-interview-university

**Comment by fadilmamedov** [comment]
I would start from **Additional Books** section if you don't mind. But what should I do when I have that piece of translation finished? I currently have a fork of **jwasham/coding-interview-university**.

**Comment by Ilyushin** [comment]
@fadilmamedov You need to fork this https://github.com/Ilyushin/google-interview-university When you will have translated your section, you need to create a pull request.

**Comment by fadilmamedov** [comment]
Sorry, it might be a stupid question, but why should I create a PR to https://github.com/Ilyushin/google-interview-university instead of original https://github.com/jwasham/coding-interview-university?

**Comment by Ilyushin** [comment]
@fadilmamedov Yes, exactly! When we will have translated all text, John accept our changes via  https://github.com/jwasham/coding-interview-university/pull/88

**Comment by fadilmamedov** [comment]
@Ilyushin, thanks for clarification. I will update you once I have that part of text translated!

**Comment by Ilyushin** [comment]
@fadilmamedov You're welcome:) Thank you for your help!

**Comment by RadomirDuo** [comment]
Thanks! Guy!!!

**Comment by rtrv** [comment]
Hi, @Ilyushin. Is there any topic to help with? I'd like to participate

**Comment by Ilyushin** [comment]
Hi, @rtrv! Yes, certainly, you can choose any starting from combinatorics.

**Comment by rtrv** [comment]
@Ilyushin ok. Could you made a checklist at first post for all the topics? Checked for done, unchecked for undone and explicitly marked WIP with username for sections in progress? It helps with coordination a lot. We used such list here: https://github.com/wunsh/elixir-docs-ru/issues/6

As I can conclude, people use your fork to work on Russian translation. Could you rebase it to upstream master branch? It's outdated

**Comment by Ilyushin** [comment]
@rtrv Ok, I will update current branch from original and create a checklist. Thank you a lot for your advice and helping:)

**Comment by Ilyushin** [comment]
@rtrv Done

**Comment by rtrv** [comment]
@Ilyushin good! Could you also mark finished sections? And assign the following to me:
* Combinatorics (n choose k) & Probability
* NP, NP-Complete and Approximation Algorithms
* Caches
* Processes and Threads
* Papers

Like:

- [ ] Topic name (@rtrv)

It's also convinient to highlight unstarted and unassigned sections with making it **bold**

PS I plan to work on a tool to make it easy to work with translation of markdown files. It's too hard when you translate some tutorials/documentation which original version has often updates. If anyone is interested in this, write me on Gitter

**Comment by Ilyushin** [comment]
@rtrv no doubt man, I'll ping you.
For marking section I need more time because I have to check discrepancies after the updating from the original and fix them if it's needed.

**Comment by pr0minence** [comment]
@Ilyushin Hey, how are things going with translation?

**Comment by cup-0f-tea** [comment]
i can help aswell

**Comment by Ilyushin** [comment]
@pr0minence Hey man! We have been continued translating if you want to help, you are welcome:)

**Comment by Ilyushin** [comment]
@pr0minence You can check items which you are planning to translate and write near your nickname

**Comment by Ilyushin** [comment]
@lowest-fi-ever thanks man! You can check items which you are planning to translate and write near your nickname.

**Comment by mikhailusov** [comment]
Available to help.

**Comment by Ilyushin** [comment]
@mikhailusov It's cool, thank you:) You can choose appropriate items from the list above, mark them and write near to them your nickname.

**Comment by mikhailusov** [comment]
@Ilyushin I can't edit your comment, so I will have to ask you to do so. This is topics I'd like to be assigned for now:
>  Final Review
>  Coding Question Practice
>  Coding exercises/challenges
>  Once you're closer to the interview
>  Your Resume
>  Be thinking of for when the interview comes
>  Have questions for the interviewer
>  Once You've Got The Job

**Comment by Ilyushin** [comment]
@mikhailusov Done

**Comment by g7tro4w** [comment]
Hi. I wanna help with translation. What can i do for you?

**Comment by Ilyushin** [comment]
Hi @g7tro4w! It's cool:) You can choose appropriate items from the list above and write me which of them, fork https://github.com/Ilyushin/google-interview-university and when you will be ready to create a new pull request.

**Comment by g7tro4w** [comment]
@Ilyushin I'll translate this topics:
-  Testing
-  Scheduling
-  Implement system routines
-  String searching & manipulations
-  Tries
-  Floating Point Numbers
-  Unicode
-  Endianness
-  Networking
-  System Design, Scalability, Data Handling (if you have 4+ years experience)

**Comment by Ilyushin** [comment]
@g7tro4w Done

**Comment by Ilyushin** [comment]
@rtrv @g7tro4w @mikhailusov Do you have any news about translations?

**Comment by rtrv** [comment]
@Ilyushin seems like I've missed a message on translated document structure update according to changed source. Is it actual now?

**Comment by Ilyushin** [comment]
@rtrv Thanks for the reference to the project, it's interesting.
About the conformity, what do you mean by the source? John's project or our branch?

**Comment by rtrv** [comment]
@Ilyushin I mean English John's project as the source, so the traslation should have at least the same structure to work on it. As I remember there was structure difference to be fixed before translating particular topics

**Comment by mikhailusov** [comment]
@Ilyushin sorry been busy with other stuff will try to finish next week.

**Comment by PandaJules** [comment]
Hi, I would like to help with translation! I will try on some of the unchecked topics and will submit a PR https://github.com/Ilyushin/google-interview-university

I was wondering if I could re-word some of the existing parts? I know we are translating from English and sometimes there just isn't a nice word, but a lot of it sounds very unnatural and dry in Russian...

**Comment by Ilyushin** [comment]
Hi @PandaJules 
Thank you a lot for your helping. Yes, sure, if you find any misunderstood places in the translation, please, fix them.

**Comment by Gahtungr** [comment]
Can I get acquainted with the already translated parts?

**Comment by Ilyushin** [comment]
@Gahtungr Hi man! Yes, you can check the list of topics in the first message of this issue.

**Comment by MaximKazionov** [comment]
Hi^
Can I help you with translation?

**Comment by Ilyushin** [comment]
> Hi^
> Can I help you with translation?

Hi @kazionovm !
Certainly, you can choose any not tagged items from the list of content and translate it, then you need to create a pull request. Link to the repository https://github.com/Ilyushin/google-interview-university.

**Comment by askeroff** [comment]
Hi, I thought this repo would be translated already :D. Is this still going on? A lot of what's left seem to be just links, shall I take some of it? Or is considered to be done? @Ilyushin

**Comment by rtrv** [comment]
@Ilyushin in order to complete Hactoberfest I'd like to take the following parts:
1. Unix command line tools
2. Information theory
3. Parity & Hamming Code
4. Entropy

**Comment by Ilyushin** [comment]
@rtrv You can take:
1. AVL trees
2. Splay trees
3.  Red/black trees
4. 2-3 search trees

Is it ok for you?

**Comment by Ilyushin** [comment]
@askeroff Hi man! You can take the following:

1. 2-3-4 Trees (aka 2-4 trees)
2. N-ary (K-ary, M-ary) trees
3. B-Trees
4. k-D Trees
5. Skip lists
6. Network Flows
7. Disjoint Sets & Union Find
8.  Math for Fast Processing
9.  Treap

Please, message me if it works for you.

**Comment by rtrv** [comment]
@Ilyushin yep, I'm in

**Comment by askeroff** [comment]
@Ilyushin , Hi, awesome.  Sure, I think I'll start working on those top to bottom.

**Comment by askeroff** [comment]
@Ilyushin anything non taken left can be translated right?

Locality-Sensitive Hashing
 van Emde Boas Trees
 Augmented Data Structures
 Geometry, Convex hull

**Comment by Ilyushin** [comment]
> @Ilyushin anything non taken left can be translated right?
> 
> Locality-Sensitive Hashing
> van Emde Boas Trees
> Augmented Data Structures
> Geometry, Convex hull

@askeroff Yes

**Comment by hoopengo** [comment]
@Hoopengo:

> maybe, I translate too

**Comment by Ilyushin** [comment]
@hoopengo yes, certainly.

**Comment by jwasham** [comment]
Will close this due to age. Thanks for your contributions!
