### ISSUE TITLE
I have a new detailed explanation about the distributed video, can I upload it?

### ISSUE THREAD

**Issue by leikang123** [jwasham/coding-interview-university#895]
I have a new detailed explanation about the distributed video, can I upload it?
This video is better to listen to。
Attach link  ：https://www.youtube.com/channel/UC_7WrbZTCODu1o_kfUMq88g

**Comment by jwasham** [comment]
I see this as the playlist for the course: https://www.youtube.com/watch?v=cQP8WApzIQQ&list=PLrw6a1wE39_tb2fErI4-WkMbsvGQk9_UB

I can add that one. Thank you. It's nice to have recent courses!
