### ISSUE TITLE
image link leads to 404

### ISSUE THREAD

**Issue by IvanReznikov** [jwasham/coding-interview-university#914]
Bug

Readme 404:

In the russian readme the link for the image is broken: https://camo.githubusercontent.com/a1c482caa5cc3e6db6abfcb2dc19db32e3eda126127d28a2439aa0772cb96139/68747470733a2f2f646e67356c33717a7265616c362e636c6f756466726f6e742e6e65742f323031362f4175672f636f64696e675f626f6172645f736d616c6c2d313437303836363336393131382e6a7067

**Comment by jwasham** [comment]
Thank you! Updated.
