### ISSUE TITLE
Recommend a good RP to read global computer papers:

### ISSUE THREAD

**Issue by lingsheng001** [jwasham/coding-interview-university#922]
1000+ copies of computer paper, Carnegie Mellon University, University of Chicago, Facebook, Google, Microsoft, Twitter and other great work, constantly updated...
https://github.com/0voice/computer_expert_paper

**Comment by jwasham** [comment]
Thank you! This is a big list! I'll add it in the Papers section.

**Comment by lingsheng001** [comment]
Thanks!
