### ISSUE TITLE
Want to Change Some Links 

### ISSUE THREAD

**Issue by leelmamta** [jwasham/coding-interview-university#956]
Some of the links like Resume building and others are expired , I wish to change those links.

**Comment by jwasham** [comment]
Thanks. Please open a pull request.

**Comment by francisd360** [comment]
Hello am new here I don't understand anything here and what is this app use for

**Comment by leelmamta** [comment]
> Hello am new here I don't understand anything here and what is this app use for

This repository is to prepare for google interview. In this owner is telling about how he is preparing for google and how a non-cs student can prepare for google.

**Comment by francisd360** [comment]
ok thanks I thought GitHub is where some termux command tool where created

**Comment by Shujasheikh** [comment]
> Hello am new here I don't understand anything here and what is this app use for

Github is self-study platform

**Comment by jwasham** [comment]
Closing this.
