### ISSUE TITLE
Moving translations

### ISSUE THREAD

**Issue by jwasham** [jwasham/coding-interview-university#97]
As the number of translations is growing like crazy, I want to keep it organized. Please move your translations to the new translations directory.

The oldest translation is the Chinese translation. @aleen42 @Newt0n @bobmayuze @laobie @sqrthree. Please move the file to the translation directory and update your any links to the old file. 

Sorry for the trouble!

**Comment by ToJen** [comment]
Hello, how can I make a translation? Especially for a language that isn't so popular.

**Comment by jwasham** [comment]
@ToJen Here you go: #125 
Thanks!
